In [27]:
import numpy as np


j = np.ones(10) + 1


In [28]:
import math
import numpy.linalg as la
from sklearn import metrics

def get_alpha( XX, X_mn, n):
    return 1 / n * la.pinv(XX) @ X_mn @ np.ones((n, 1))

def get_bucket_content(X, m=0):
    n = len(X)
    X = X.reshape(1, -1)
    if m == 0:
        m = round(math.sqrt(n))
    m_idx = np.random.default_rng().integers(n, size=m)
    X_tilde = X[m_idx]
    X_mn = metrics.pairwise.rbf_kernel(X_tilde, X)
    alpha = get_alpha(X, X_mn, n)
    return X_tilde, alpha, m

In [29]:
X = np.array([1])
print(X)

[1]


In [30]:
get_bucket_content( X)

(array([[1]]), array([[1.]]), 1)

In [31]:
kl = np.array([1,2])
kl.shape
kl

array([1, 2])

In [32]:
kl = np.array([1,2])
kl = np.array([kl])
kl.shape

(1, 2)

In [33]:
kl


array([[1, 2]])

In [34]:
A = [[6, 7],
      [8, 9]]

B = [[1],[0]]


In [35]:
kek = np.array(A) @ np.array(B)
print(kek)
print(kek.flatten())

[[6]
 [8]]
[6 8]


In [36]:
import numpy.linalg as la
threeByTwoMatrix = np.array([[1, 0] ,[0,1], [1,1]])
vector = np.array([2,4])
print(threeByTwoMatrix @ vector)
print(la.pinv(threeByTwoMatrix) @ threeByTwoMatrix)

[2 4 6]
[[1.00000000e+00 1.11022302e-16]
 [1.11022302e-16 1.00000000e+00]]


In [60]:
def k(x, y):
    return metrics.pairwise.rbf_kernel(x,y)

first , second = [[1,2],[3,3]], [[1,3],[4,4]]

M = k(first,second)
print(M)
a = np.array([1])
b = np.array([2,2,3,4])
np.concatenate((a,b))

[[0.60653066 0.00150344]
 [0.13533528 0.36787944]]


array([1, 2, 2, 3, 4])

In [67]:
A = np.array([[1,0],[0,1]])
A @ (.5 * A)

array([[0.5, 0. ],
       [0. , 0.5]])