In [3]:
import numpy as np

k = range(10)
j = np.ones(10) + 1
for i in k:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [26]:
import math
import numpy.linalg as la
from sklearn import metrics

def get_alpha( XX, X_mn, n):
    return 1 / n * la.pinv(XX) @ X_mn @ np.ones((n, 1))

def get_bucket_content(X, m=0):
    n = len(X)
    X = X.reshape(1, -1)
    if m == 0:
        m = round(math.sqrt(n))
    m_idx = np.random.default_rng().integers(n, size=m)
    X_tilde = X[m_idx]
    X_mn = metrics.pairwise.rbf_kernel(X_tilde, X)
    alpha = get_alpha(X, X_mn, n)
    return X_tilde, alpha, m

In [27]:
X = np.array([1])
print(X)

[1]


In [39]:
get_bucket_content( X)

(array([[1]]), array([[1.]]), 1)

In [43]:
kl = np.array([1,2])
kl.shape
kl

array([1, 2])

In [44]:
kl = np.array([1,2])
kl = np.array([kl])
kl.shape

(1, 2)

In [45]:
kl


array([[1, 2]])